import type { Metadata } from "next";
import "@/app/globals.css";
import OpenSans from "@/app/fonts/OpenSansFont";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OpenSans.className} antialiased`}>
        <div className="flex w-screen h-screen justify-center align-middle">
          <div className="w-1/2 py-5">
            <Header />
            <div>{children}</div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
